# Adapted from https://github.com/rsyslog/rsyslog-docker/blob/master/appliance/alpine/Dockerfile
FROM rsyslog/syslog_appliance_alpine
COPY config/rsyslog.conf /etc/rsyslog.conf
COPY config/trencat.conf /etc/rsyslog.d/

