#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_TRENCAT_USER;
	CREATE DATABASE $POSTGRES_TRENCAT_DB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_TRENCAT_DB TO $POSTGRES_TRENCAT_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_TRENCAT_USER" --dbname "$POSTGRES_TRENCAT_DB" -f /init.sql
